
AKA_VERSION_LOADED = "AKA %s loaded"
AKA_ENABLED_MAIN_BLANK = "AKA enabled for this channel but main is blank"
AKA_ENABLED = "AKA enabled"
AKA_DISABLED = "AKA disabled"
AKA_DISABLED_FOR_GUILD = "AKA disabled for guild chat"
AKA_ENABLED_FOR_GUILD = "AKA enabled for guild chat"
AKA_DISABLED_FOR_WHISPER = "AKA disabled for whispers"
AKA_ENABLED_FOR_WHISPER = "AKA enabled for whispers"
AKA_RESET_TO_DEFAULT = "AKA has been reset to default settings for all realms"
AKA_COMMAND_NOT_RECOGNIZED = "AKA command '%s' not recognized"
AKA_MAIN_SET_VALUE = "AKA value for main updated from '%s' to '%s'"

AKA_HELP_PREAMBLE = "This is the help for the AKA AddOn.\nSee README for more information"
AKA_HELP_NOARG = "/aka - Displays basic help information"
AKA_HELP_HELP = "/aka help - Displays basic help information"
AKA_HELP_GUILD = "/aka guild - Toggle display of moniker on and off for guild chat for the current faction on the current realm"
AKA_HELP_WHISPER = "/aka whisper - Toggle display of moniker on/off for whispers for the current faction on the current realm"
AKA_HELP_MAIN = "/aka main <name> - Sets the name of your main for the current faction on the current realm"
AKA_HELP_ON = "/aka on - Enable the AKA AddOn for the current realm"
AKA_HELP_OFF = "/aka off - Disable the AKA AddOn for the current realm"
AKA_HELP_RESET = "/aka reset - Reset the current faction on the current realm to the default values"
