
MONIKER_VERSION_LOADED = "Moniker %s loaded"
MONIKER_ENABLED_MAIN_BLANK = "Moniker enabled for this channel but main is blank"
MONIKER_ENABLED = "Moniker enabled"
MONIKER_DISABLED = "Moniker disabled"
MONIKER_DISABLED_FOR_GUILD = "Moniker disabled for guild chat"
MONIKER_ENABLED_FOR_GUILD = "Moniker enabled for guild chat"
MONIKER_DISABLED_FOR_WHISPER = "Moniker disabled for whispers"
MONIKER_ENABLED_FOR_WHISPER = "Moniker enabled for whispers"
MONIKER_RESET_TO_DEFAULT = "Moniker has been reset to default settings for all realms"
MONIKER_COMMAND_NOT_RECOGNIZED = "Moniker command '%s' not recognized"
MONIKER_MAIN_SET_VALUE = "Moniker value for main updated from '%s' to '%s'"

MONIKER_HELP_PREAMBLE = "This is the help for the Moniker AddOn.\nSee README for more information"
MONIKER_HELP_NOARG = "/mnk - Displays basic help information"
MONIKER_HELP_HELP = "/mnk help - Displays basic help information"
MONIKER_HELP_GUILD = "/mnk guild - Toggle display of moniker on and off for guild chat for the current faction on the current realm"
MONIKER_HELP_WHISPER = "/mnk whisper - Toggle display of moniker on/off for whispers for the current faction on the current realm"
MONIKER_HELP_MAIN = "/mnk main <name> - Sets the name of your main for the current faction on the current realm"
MONIKER_HELP_ON = "/mnk on - Enable the Moniker AddOn for the current realm"
MONIKER_HELP_OFF = "/mnk off - Disable the Moniker AddOn for the current realm"
MONIKER_HELP_RESET = "/mnk reset - Reset the current faction on the current realm to the default values"
